### ISSUE TITLE
Plugin does not work With RowExpander of Extjs 4.1.2

### ISSUE THREAD

**Issue by loiane** [loiane/extjs4-ux-gridprinter#10]
Ext.each(grid.plugins, function(p) {
                if (p.ptype == 'rowexpander') {
                    pluginsBody += p.rowBodyTpl.join(''); //In 4.1.2 rowBodyTpl is a  XTemplate object
                }
            });

http://www.sencha.com/forum/showthread.php?146348-ExtJS-4-Grid-Printer-Plugin&p=900321&viewfull=1#post900321

**Comment by Marthy-M** [comment]
In my case, p.rowBodyTpl has html property, so this could work in most cases:
                if (p.ptype == 'rowexpander') {
					if (Array.isArray(p.rowBodyTpl)) {
						pluginsBody += p.rowBodyTpl.join(''); // for older ExtJS versions
					}
					else {
						pluginsBody += p.rowBodyTpl.html; // for ExtJS 4.1.2 and newer
					}
                }

**Comment by loiane** [comment]
Thanks. Could you pls submit a pull request?

**Comment by Marthy-M** [comment]
I will, as soon as I verify that it should actually work generally and that it is the best solution.
