### ISSUE TITLE
Summary row plugin - summary row not showing in printout

### ISSUE THREAD

**Issue by paultorben** [loiane/extjs4-ux-gridprinter#11]
I make use of the Summary Row Plugin for ExtJS 4 Grids, but these do not show up in the print out.  Ps.  love this UX extension, thanks so much for creating it!

**Comment by me21** [comment]
@TexasSteve99 are you referring to this grid printer (this repository)? It didn't print grouping summary for me using ExtJS 6.2.0, I can post my source here if necessary.
