### ISSUE TITLE
Issue using printAutomatically = true

### ISSUE THREAD

**Issue by jperuggia** [loiane/extjs4-ux-gridprinter#28]
When setting to true, in chrome, the print window will not have any contents. This can be fixed by moving `win.document.close` inside Printer.js to after
 `if (this.printAutomatically){`
`win.print();`
`}`

**Comment by bereachad** [comment]
Seems as it still shows up as blank for large datasets.

**Comment by TexasSteve99** [comment]
Someone else will need to fix this as I am in ICU for the last three weeks.  She will not be getting out anytime soon.

Steve

**Comment by chamacs** [comment]
The print option has to be triggered after the document is completely loaded in the new window.  I solved this by moving the auto printing logic to the htmlMarkup template:
````
// after the <title> line ...
                    '<script type="text/javascript">',
                    	'function printOnload() {',
                        	'if (' + this.printAutomatically + ') {',
                            	'window.print();',
                                'if (' + this.closeAutomaticallyAfterPrint + '){',
                                	'window.close();',
                                '}',
                            '}',
                        '}',
                    '</script>',
                  '</head>',
// added the onload attribute to call the function once the page is loaded ....
                  '<body class="' + Ext.baseCSSPrefix + 'ux-grid-printer-body" onload="printOnload();">',
````

Also removed all the 'auto print' logic from the end of the print method.  The end just looks like:
````
            //document must be open and closed
            win.document.open();
            win.document.write(html);
            win.document.close();
        },
````
Hope this helps.

**Comment by loiane** [comment]
Please submit a PR with your solution. Thanks!

**Comment by chamacs** [comment]
PR created, as requested.
