### ISSUE TITLE
Imprimir cabeçalhos agrupados - Print grouped headers

### ISSUE THREAD

**Issue by joseqfneto** [loiane/extjs4-ux-gridprinter#29]
Olá, Loiane!

Spencer e você fizeram um bom trabalho! Parabéns!
Estou usando o ux-gridprinter e funciona muito bem pra mim. Mas no caso de cabeçalhos agrupados ele imprime apenas uma linha do cabeçalho...

Bom, queria saber se há possibilidade de imprimir cabeçalhos agrupados das grids com o ux-printgrid.

Segue em anexo um exemplo.

Obrigado!!

![grid print](https://cloud.githubusercontent.com/assets/14347145/9959246/bd360340-5de8-11e5-9c96-e29d28a9e1a2.png)
.

**Comment by loiane** [comment]
Oi joseqfneto, vc pode fazer as modificações necessárias nesse plugin para que funcione no seu projeto.

**Comment by joseqfneto** [comment]
Oi, Loiane! Eu imaginei que poderia ter uma opção já pronta mas depois vi que só implementando mesmo. Vou começar a implementar.
Obrigado pela atenção!
