### ISSUE TITLE
Template Column and grouping summaries stops data output

### ISSUE THREAD

**Issue by Eibborest** [loiane/extjs4-ux-gridprinter#31]
Change for around line 706 to fix this. 

if (column.renderer && column.xtype != 'templatecolumn')
	value = column.renderer.call(this.grid, value, meta, rcd, -1, col - 1, this.grid.store, this.grid.view);
else if (column.renderer && column.xtype == 'templatecolumn')
	value = column.tpl.apply(rcd.data);

**Comment by loiane** [comment]
Hi @Eibborest  - thanks for your comment. Can you please submit a pull request with this fix?

Thanks!
