### ISSUE TITLE
Extjs 6.2 build failed

### ISSUE THREAD

**Issue by ajmakoni** [loiane/extjs4-ux-gridprinter#35]
Hello,
I have been trying to intergrate the plugin to my project to print one grid. I have added the ux to ext/classic/classic/src/ux/grid . Eachtime I ran the application I get this error: [ERR] C2008: Requirement had no matching files (Ext.grid.feature.RowWrap)  and this  [ERR] com.sencha.exceptions.ExBuild: Failed to find any files for C:\app\ext\classic\classic\src\ux\RowExpander.js::ClassRequire::Ext.grid.feature.RowWrap is missing.
Is this plugin compatible with Extjs 6.2 and CMD 6.5?

**Comment by abenhamdine** [comment]
Hi,

I think this repo is not actively maintained.
FWIW, we don't use Sencha Cmd, but we maintain a fork of this plugin, see https://github.com/Arhia/Ext.ux.grid.Printer

**Comment by ajmakoni** [comment]
Hi, thanks for your feedback. I will use your repo 👍 💯

**Comment by loiane** [comment]
Don't use the RowExpander plugin from this repo, use the one from Sencha lib. This RowExpander code is for ExtJS 4.x (when the plugin was not officially part of the API).

The only code you need for your 6.x app is ux/grid/Printer.js + CSS.

**Comment by ajmakoni** [comment]
Thanks for the feedback Loiane. Removing RowExpander.js file resolved the issue
